version: '3'

services:
  app:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: alloy:4318
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - alloy
    networks:
      - tpm

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./minio-data:/data
    command: server /data
    networks:
      - tpm

  alloy:
    image: grafana/alloy:latest
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./logs:/tmp/app-logs/
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - tpm
  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - tpm
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - tpm

volumes:
  loki-data:

networks:
    tpm: