graph:
  connectors:
    feed-message-connector:
    vp-connector:
    se-connector:
    headway-connector:
    dwell-connector:
    travel-time-connector:

  sources:
    mbta-vehicle-positions:
      type: "http"
      http:
        url: "https://cdn.mbta.com/realtime/VehiclePositions.pb"
        interval: "1s"
    mta-vehicle-positions:
      type: "http"
      http:
        url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace"
        interval: "1s"

  sinks:
    console-sink:
      type: "console"
      console:
        level: "info"
    sse-sink:
      type: "sse"
      sse:
        port: "8080"
        path: "/events"

  pipelines:
    mbta-feed-message-pipeline:
      id: "mbta-feed-message-pipeline"
      agency_id: "MBTA"
      type: "feed_message"
      sources: ["mbta-vehicle-positions"]
      state_store: "mbta-feed-message-state-store"
      sinks: ["feed-message-connector"]

    mta-feed-message-pipeline:
      id: "mta-feed-message-pipeline"
      agency_id: "MTA"
      type: "feed_message"
      sources: ["mta-vehicle-positions"]
      state_store: "mta-feed-message-state-store"
      sinks: ["feed-message-connector"]

    vp-pipeline:
      id: "vp-pipeline"
      type: "vehicle_position"
      sources: ["feed-message-connector"]
      state_store: "vp-state-store"
      sinks: ["vp-connector", "console-sink", "sse-sink"]

    se-pipeline:
      id: "se-pipeline"
      type: "stop_event"
      sources: ["vp-connector"]
      state_store: "se-state-store"
      sinks: ["headway-connector", "dwell-connector", "travel-time-connector", "console-sink", "sse-sink"]

    headway-pipeline:
      id: "headway-pipeline"
      type: "headway_event"
      sources: ["headway-connector"]
      state_store: "headway-state-store"
      sinks: ["console-sink", "sse-sink"]

    dwell-pipeline:
      id: "dwell-pipeline"
      type: "dwell_event"
      sources: ["dwell-connector"]
      state_store: "dwell-state-store"
      sinks: ["console-sink", "sse-sink"]

    travel-time-pipeline:
      id: "travel-time-pipeline"
      type: "travel_time"
      sources: ["travel-time-connector"]
      state_store: "travel-time-state-store"
      sinks: ["console-sink", "sse-sink"]
