// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/v1/events/transit.proto

package events

import (
	gtfs "github.com/MobilityData/gtfs-realtime-bindings/golang/gtfs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopStatus int32

const (
	StopStatus_UNKNOWN       StopStatus = 0
	StopStatus_INCOMING_AT   StopStatus = 1
	StopStatus_STOPPED_AT    StopStatus = 2
	StopStatus_IN_TRANSIT_TO StopStatus = 3
)

// Enum value maps for StopStatus.
var (
	StopStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "INCOMING_AT",
		2: "STOPPED_AT",
		3: "IN_TRANSIT_TO",
	}
	StopStatus_value = map[string]int32{
		"UNKNOWN":       0,
		"INCOMING_AT":   1,
		"STOPPED_AT":    2,
		"IN_TRANSIT_TO": 3,
	}
)

func (x StopStatus) Enum() *StopStatus {
	p := new(StopStatus)
	*p = x
	return p
}

func (x StopStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_events_transit_proto_enumTypes[0].Descriptor()
}

func (StopStatus) Type() protoreflect.EnumType {
	return &file_api_v1_events_transit_proto_enumTypes[0]
}

func (x StopStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopStatus.Descriptor instead.
func (StopStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{0}
}

// Event type
type StopEvent_EventType int32

const (
	StopEvent_UNKNOWN   StopEvent_EventType = 0
	StopEvent_ARRIVAL   StopEvent_EventType = 1
	StopEvent_DEPARTURE StopEvent_EventType = 2
)

// Enum value maps for StopEvent_EventType.
var (
	StopEvent_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ARRIVAL",
		2: "DEPARTURE",
	}
	StopEvent_EventType_value = map[string]int32{
		"UNKNOWN":   0,
		"ARRIVAL":   1,
		"DEPARTURE": 2,
	}
)

func (x StopEvent_EventType) Enum() *StopEvent_EventType {
	p := new(StopEvent_EventType)
	*p = x
	return p
}

func (x StopEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_events_transit_proto_enumTypes[1].Descriptor()
}

func (StopEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_v1_events_transit_proto_enumTypes[1]
}

func (x StopEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopEvent_EventType.Descriptor instead.
func (StopEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{5, 0}
}

type FeedMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgencyId      string                 `protobuf:"bytes,1,opt,name=agency_id,json=agencyId,proto3" json:"agency_id,omitempty"`
	FeedMessage   *gtfs.FeedMessage      `protobuf:"bytes,2,opt,name=feed_message,json=feedMessage,proto3" json:"feed_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedMessageEvent) Reset() {
	*x = FeedMessageEvent{}
	mi := &file_api_v1_events_transit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedMessageEvent) ProtoMessage() {}

func (x *FeedMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedMessageEvent.ProtoReflect.Descriptor instead.
func (*FeedMessageEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{0}
}

func (x *FeedMessageEvent) GetAgencyId() string {
	if x != nil {
		return x.AgencyId
	}
	return ""
}

func (x *FeedMessageEvent) GetFeedMessage() *gtfs.FeedMessage {
	if x != nil {
		return x.FeedMessage
	}
	return nil
}

type FeedMessageEventCollection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeedMessageEvents []*FeedMessageEvent    `protobuf:"bytes,1,rep,name=feed_message_events,json=feedMessageEvents,proto3" json:"feed_message_events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeedMessageEventCollection) Reset() {
	*x = FeedMessageEventCollection{}
	mi := &file_api_v1_events_transit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedMessageEventCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedMessageEventCollection) ProtoMessage() {}

func (x *FeedMessageEventCollection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedMessageEventCollection.ProtoReflect.Descriptor instead.
func (*FeedMessageEventCollection) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{1}
}

func (x *FeedMessageEventCollection) GetFeedMessageEvents() []*FeedMessageEvent {
	if x != nil {
		return x.FeedMessageEvents
	}
	return nil
}

type EventAttributes struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgencyId             string                 `protobuf:"bytes,1,opt,name=agency_id,json=agencyId,proto3" json:"agency_id,omitempty"`
	VehicleId            string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	RouteId              string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	StopId               string                 `protobuf:"bytes,4,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	OriginStopId         string                 `protobuf:"bytes,5,opt,name=origin_stop_id,json=originStopId,proto3" json:"origin_stop_id,omitempty"`
	DestinationStopId    string                 `protobuf:"bytes,6,opt,name=destination_stop_id,json=destinationStopId,proto3" json:"destination_stop_id,omitempty"`
	DirectionId          string                 `protobuf:"bytes,7,opt,name=direction_id,json=directionId,proto3" json:"direction_id,omitempty"`
	Direction            string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	DirectionDestination string                 `protobuf:"bytes,9,opt,name=direction_destination,json=directionDestination,proto3" json:"direction_destination,omitempty"`
	ParentStation        string                 `protobuf:"bytes,10,opt,name=parent_station,json=parentStation,proto3" json:"parent_station,omitempty"`
	StopSequence         int32                  `protobuf:"varint,11,opt,name=stop_sequence,json=stopSequence,proto3" json:"stop_sequence,omitempty"`
	StopStatus           StopStatus             `protobuf:"varint,12,opt,name=stop_status,json=stopStatus,proto3,enum=transit.events.StopStatus" json:"stop_status,omitempty"`
	TripId               string                 `protobuf:"bytes,13,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	ServiceDate          string                 `protobuf:"bytes,15,opt,name=service_date,json=serviceDate,proto3" json:"service_date,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventAttributes) Reset() {
	*x = EventAttributes{}
	mi := &file_api_v1_events_transit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAttributes) ProtoMessage() {}

func (x *EventAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAttributes.ProtoReflect.Descriptor instead.
func (*EventAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{2}
}

func (x *EventAttributes) GetAgencyId() string {
	if x != nil {
		return x.AgencyId
	}
	return ""
}

func (x *EventAttributes) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *EventAttributes) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *EventAttributes) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *EventAttributes) GetOriginStopId() string {
	if x != nil {
		return x.OriginStopId
	}
	return ""
}

func (x *EventAttributes) GetDestinationStopId() string {
	if x != nil {
		return x.DestinationStopId
	}
	return ""
}

func (x *EventAttributes) GetDirectionId() string {
	if x != nil {
		return x.DirectionId
	}
	return ""
}

func (x *EventAttributes) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *EventAttributes) GetDirectionDestination() string {
	if x != nil {
		return x.DirectionDestination
	}
	return ""
}

func (x *EventAttributes) GetParentStation() string {
	if x != nil {
		return x.ParentStation
	}
	return ""
}

func (x *EventAttributes) GetStopSequence() int32 {
	if x != nil {
		return x.StopSequence
	}
	return 0
}

func (x *EventAttributes) GetStopStatus() StopStatus {
	if x != nil {
		return x.StopStatus
	}
	return StopStatus_UNKNOWN
}

func (x *EventAttributes) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *EventAttributes) GetServiceDate() string {
	if x != nil {
		return x.ServiceDate
	}
	return ""
}

func (x *EventAttributes) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type VehiclePositionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    *EventAttributes       `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclePositionEvent) Reset() {
	*x = VehiclePositionEvent{}
	mi := &file_api_v1_events_transit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclePositionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclePositionEvent) ProtoMessage() {}

func (x *VehiclePositionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclePositionEvent.ProtoReflect.Descriptor instead.
func (*VehiclePositionEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{3}
}

func (x *VehiclePositionEvent) GetAttributes() *EventAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *VehiclePositionEvent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *VehiclePositionEvent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type VehiclePositionEventCollection struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	VehiclePositionEvents []*VehiclePositionEvent `protobuf:"bytes,1,rep,name=vehicle_position_events,json=vehiclePositionEvents,proto3" json:"vehicle_position_events,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VehiclePositionEventCollection) Reset() {
	*x = VehiclePositionEventCollection{}
	mi := &file_api_v1_events_transit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclePositionEventCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclePositionEventCollection) ProtoMessage() {}

func (x *VehiclePositionEventCollection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclePositionEventCollection.ProtoReflect.Descriptor instead.
func (*VehiclePositionEventCollection) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{4}
}

func (x *VehiclePositionEventCollection) GetVehiclePositionEvents() []*VehiclePositionEvent {
	if x != nil {
		return x.VehiclePositionEvents
	}
	return nil
}

type StopEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    *EventAttributes       `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	StopEventType StopEvent_EventType    `protobuf:"varint,14,opt,name=stop_event_type,json=stopEventType,proto3,enum=transit.events.StopEvent_EventType" json:"stop_event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEvent) Reset() {
	*x = StopEvent{}
	mi := &file_api_v1_events_transit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEvent) ProtoMessage() {}

func (x *StopEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEvent.ProtoReflect.Descriptor instead.
func (*StopEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{5}
}

func (x *StopEvent) GetAttributes() *EventAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *StopEvent) GetStopEventType() StopEvent_EventType {
	if x != nil {
		return x.StopEventType
	}
	return StopEvent_UNKNOWN
}

type StopEventCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopEvents    []*StopEvent           `protobuf:"bytes,1,rep,name=stop_events,json=stopEvents,proto3" json:"stop_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEventCollection) Reset() {
	*x = StopEventCollection{}
	mi := &file_api_v1_events_transit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEventCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEventCollection) ProtoMessage() {}

func (x *StopEventCollection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEventCollection.ProtoReflect.Descriptor instead.
func (*StopEventCollection) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{6}
}

func (x *StopEventCollection) GetStopEvents() []*StopEvent {
	if x != nil {
		return x.StopEvents
	}
	return nil
}

type DwellTimeEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Attributes       *EventAttributes       `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	ArrivalTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	DepartureTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	DwellTimeSeconds int32                  `protobuf:"varint,4,opt,name=dwell_time_seconds,json=dwellTimeSeconds,proto3" json:"dwell_time_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DwellTimeEvent) Reset() {
	*x = DwellTimeEvent{}
	mi := &file_api_v1_events_transit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DwellTimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DwellTimeEvent) ProtoMessage() {}

func (x *DwellTimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DwellTimeEvent.ProtoReflect.Descriptor instead.
func (*DwellTimeEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{7}
}

func (x *DwellTimeEvent) GetAttributes() *EventAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *DwellTimeEvent) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *DwellTimeEvent) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *DwellTimeEvent) GetDwellTimeSeconds() int32 {
	if x != nil {
		return x.DwellTimeSeconds
	}
	return 0
}

type DwellTimeEventCollection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DwellTimeEvents []*DwellTimeEvent      `protobuf:"bytes,1,rep,name=dwell_time_events,json=dwellTimeEvents,proto3" json:"dwell_time_events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DwellTimeEventCollection) Reset() {
	*x = DwellTimeEventCollection{}
	mi := &file_api_v1_events_transit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DwellTimeEventCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DwellTimeEventCollection) ProtoMessage() {}

func (x *DwellTimeEventCollection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DwellTimeEventCollection.ProtoReflect.Descriptor instead.
func (*DwellTimeEventCollection) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{8}
}

func (x *DwellTimeEventCollection) GetDwellTimeEvents() []*DwellTimeEvent {
	if x != nil {
		return x.DwellTimeEvents
	}
	return nil
}

type TravelTimeEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Attributes        *EventAttributes       `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TravelTimeSeconds int32                  `protobuf:"varint,4,opt,name=travel_time_seconds,json=travelTimeSeconds,proto3" json:"travel_time_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TravelTimeEvent) Reset() {
	*x = TravelTimeEvent{}
	mi := &file_api_v1_events_transit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TravelTimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelTimeEvent) ProtoMessage() {}

func (x *TravelTimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelTimeEvent.ProtoReflect.Descriptor instead.
func (*TravelTimeEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{9}
}

func (x *TravelTimeEvent) GetAttributes() *EventAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TravelTimeEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TravelTimeEvent) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TravelTimeEvent) GetTravelTimeSeconds() int32 {
	if x != nil {
		return x.TravelTimeSeconds
	}
	return 0
}

type TravelTimeEventCollection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TravelTimeEvents []*TravelTimeEvent     `protobuf:"bytes,1,rep,name=travel_time_events,json=travelTimeEvents,proto3" json:"travel_time_events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TravelTimeEventCollection) Reset() {
	*x = TravelTimeEventCollection{}
	mi := &file_api_v1_events_transit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TravelTimeEventCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelTimeEventCollection) ProtoMessage() {}

func (x *TravelTimeEventCollection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelTimeEventCollection.ProtoReflect.Descriptor instead.
func (*TravelTimeEventCollection) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{10}
}

func (x *TravelTimeEventCollection) GetTravelTimeEvents() []*TravelTimeEvent {
	if x != nil {
		return x.TravelTimeEvents
	}
	return nil
}

type HeadwayTimeEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Attributes *EventAttributes       `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Vehicle info
	LeadingVehicleId   string `protobuf:"bytes,2,opt,name=leading_vehicle_id,json=leadingVehicleId,proto3" json:"leading_vehicle_id,omitempty"`
	FollowingVehicleId string `protobuf:"bytes,3,opt,name=following_vehicle_id,json=followingVehicleId,proto3" json:"following_vehicle_id,omitempty"`
	// Times
	HeadwaySeconds int32 `protobuf:"varint,4,opt,name=headway_seconds,json=headwaySeconds,proto3" json:"headway_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeadwayTimeEvent) Reset() {
	*x = HeadwayTimeEvent{}
	mi := &file_api_v1_events_transit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadwayTimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadwayTimeEvent) ProtoMessage() {}

func (x *HeadwayTimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadwayTimeEvent.ProtoReflect.Descriptor instead.
func (*HeadwayTimeEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{11}
}

func (x *HeadwayTimeEvent) GetAttributes() *EventAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *HeadwayTimeEvent) GetLeadingVehicleId() string {
	if x != nil {
		return x.LeadingVehicleId
	}
	return ""
}

func (x *HeadwayTimeEvent) GetFollowingVehicleId() string {
	if x != nil {
		return x.FollowingVehicleId
	}
	return ""
}

func (x *HeadwayTimeEvent) GetHeadwaySeconds() int32 {
	if x != nil {
		return x.HeadwaySeconds
	}
	return 0
}

type HeadwayTimeEventCollection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HeadwayTimeEvents []*HeadwayTimeEvent    `protobuf:"bytes,1,rep,name=headway_time_events,json=headwayTimeEvents,proto3" json:"headway_time_events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeadwayTimeEventCollection) Reset() {
	*x = HeadwayTimeEventCollection{}
	mi := &file_api_v1_events_transit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadwayTimeEventCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadwayTimeEventCollection) ProtoMessage() {}

func (x *HeadwayTimeEventCollection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_events_transit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadwayTimeEventCollection.ProtoReflect.Descriptor instead.
func (*HeadwayTimeEventCollection) Descriptor() ([]byte, []int) {
	return file_api_v1_events_transit_proto_rawDescGZIP(), []int{12}
}

func (x *HeadwayTimeEventCollection) GetHeadwayTimeEvents() []*HeadwayTimeEvent {
	if x != nil {
		return x.HeadwayTimeEvents
	}
	return nil
}

var File_api_v1_events_transit_proto protoreflect.FileDescriptor

const file_api_v1_events_transit_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/v1/events/transit.proto\x12\x0etransit.events\x1a$third_party/gtfs/gtfs-realtime.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n" +
	"\x10FeedMessageEvent\x12\x1b\n" +
	"\tagency_id\x18\x01 \x01(\tR\bagencyId\x12@\n" +
	"\ffeed_message\x18\x02 \x01(\v2\x1d.transit_realtime.FeedMessageR\vfeedMessage\"n\n" +
	"\x1aFeedMessageEventCollection\x12P\n" +
	"\x13feed_message_events\x18\x01 \x03(\v2 .transit.events.FeedMessageEventR\x11feedMessageEvents\"\xcc\x04\n" +
	"\x0fEventAttributes\x12\x1b\n" +
	"\tagency_id\x18\x01 \x01(\tR\bagencyId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x17\n" +
	"\astop_id\x18\x04 \x01(\tR\x06stopId\x12$\n" +
	"\x0eorigin_stop_id\x18\x05 \x01(\tR\foriginStopId\x12.\n" +
	"\x13destination_stop_id\x18\x06 \x01(\tR\x11destinationStopId\x12!\n" +
	"\fdirection_id\x18\a \x01(\tR\vdirectionId\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x123\n" +
	"\x15direction_destination\x18\t \x01(\tR\x14directionDestination\x12%\n" +
	"\x0eparent_station\x18\n" +
	" \x01(\tR\rparentStation\x12#\n" +
	"\rstop_sequence\x18\v \x01(\x05R\fstopSequence\x12;\n" +
	"\vstop_status\x18\f \x01(\x0e2\x1a.transit.events.StopStatusR\n" +
	"stopStatus\x12\x17\n" +
	"\atrip_id\x18\r \x01(\tR\x06tripId\x12!\n" +
	"\fservice_date\x18\x0f \x01(\tR\vserviceDate\x128\n" +
	"\ttimestamp\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x91\x01\n" +
	"\x14VehiclePositionEvent\x12?\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x1f.transit.events.EventAttributesR\n" +
	"attributes\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"~\n" +
	"\x1eVehiclePositionEventCollection\x12\\\n" +
	"\x17vehicle_position_events\x18\x01 \x03(\v2$.transit.events.VehiclePositionEventR\x15vehiclePositionEvents\"\xcf\x01\n" +
	"\tStopEvent\x12?\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x1f.transit.events.EventAttributesR\n" +
	"attributes\x12K\n" +
	"\x0fstop_event_type\x18\x0e \x01(\x0e2#.transit.events.StopEvent.EventTypeR\rstopEventType\"4\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aARRIVAL\x10\x01\x12\r\n" +
	"\tDEPARTURE\x10\x02\"Q\n" +
	"\x13StopEventCollection\x12:\n" +
	"\vstop_events\x18\x01 \x03(\v2\x19.transit.events.StopEventR\n" +
	"stopEvents\"\x81\x02\n" +
	"\x0eDwellTimeEvent\x12?\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x1f.transit.events.EventAttributesR\n" +
	"attributes\x12=\n" +
	"\farrival_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\varrivalTime\x12A\n" +
	"\x0edeparture_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12,\n" +
	"\x12dwell_time_seconds\x18\x04 \x01(\x05R\x10dwellTimeSeconds\"f\n" +
	"\x18DwellTimeEventCollection\x12J\n" +
	"\x11dwell_time_events\x18\x01 \x03(\v2\x1e.transit.events.DwellTimeEventR\x0fdwellTimeEvents\"\xf4\x01\n" +
	"\x0fTravelTimeEvent\x12?\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x1f.transit.events.EventAttributesR\n" +
	"attributes\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12.\n" +
	"\x13travel_time_seconds\x18\x04 \x01(\x05R\x11travelTimeSeconds\"j\n" +
	"\x19TravelTimeEventCollection\x12M\n" +
	"\x12travel_time_events\x18\x01 \x03(\v2\x1f.transit.events.TravelTimeEventR\x10travelTimeEvents\"\xdc\x01\n" +
	"\x10HeadwayTimeEvent\x12?\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x1f.transit.events.EventAttributesR\n" +
	"attributes\x12,\n" +
	"\x12leading_vehicle_id\x18\x02 \x01(\tR\x10leadingVehicleId\x120\n" +
	"\x14following_vehicle_id\x18\x03 \x01(\tR\x12followingVehicleId\x12'\n" +
	"\x0fheadway_seconds\x18\x04 \x01(\x05R\x0eheadwaySeconds\"n\n" +
	"\x1aHeadwayTimeEventCollection\x12P\n" +
	"\x13headway_time_events\x18\x01 \x03(\v2 .transit.events.HeadwayTimeEventR\x11headwayTimeEvents*M\n" +
	"\n" +
	"StopStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vINCOMING_AT\x10\x01\x12\x0e\n" +
	"\n" +
	"STOPPED_AT\x10\x02\x12\x11\n" +
	"\rIN_TRANSIT_TO\x10\x03B*Z(github.com/fjlanasa/tpm-go/api/v1/eventsb\x06proto3"

var (
	file_api_v1_events_transit_proto_rawDescOnce sync.Once
	file_api_v1_events_transit_proto_rawDescData []byte
)

func file_api_v1_events_transit_proto_rawDescGZIP() []byte {
	file_api_v1_events_transit_proto_rawDescOnce.Do(func() {
		file_api_v1_events_transit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_events_transit_proto_rawDesc), len(file_api_v1_events_transit_proto_rawDesc)))
	})
	return file_api_v1_events_transit_proto_rawDescData
}

var file_api_v1_events_transit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_events_transit_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_events_transit_proto_goTypes = []any{
	(StopStatus)(0),                        // 0: transit.events.StopStatus
	(StopEvent_EventType)(0),               // 1: transit.events.StopEvent.EventType
	(*FeedMessageEvent)(nil),               // 2: transit.events.FeedMessageEvent
	(*FeedMessageEventCollection)(nil),     // 3: transit.events.FeedMessageEventCollection
	(*EventAttributes)(nil),                // 4: transit.events.EventAttributes
	(*VehiclePositionEvent)(nil),           // 5: transit.events.VehiclePositionEvent
	(*VehiclePositionEventCollection)(nil), // 6: transit.events.VehiclePositionEventCollection
	(*StopEvent)(nil),                      // 7: transit.events.StopEvent
	(*StopEventCollection)(nil),            // 8: transit.events.StopEventCollection
	(*DwellTimeEvent)(nil),                 // 9: transit.events.DwellTimeEvent
	(*DwellTimeEventCollection)(nil),       // 10: transit.events.DwellTimeEventCollection
	(*TravelTimeEvent)(nil),                // 11: transit.events.TravelTimeEvent
	(*TravelTimeEventCollection)(nil),      // 12: transit.events.TravelTimeEventCollection
	(*HeadwayTimeEvent)(nil),               // 13: transit.events.HeadwayTimeEvent
	(*HeadwayTimeEventCollection)(nil),     // 14: transit.events.HeadwayTimeEventCollection
	(*gtfs.FeedMessage)(nil),               // 15: transit_realtime.FeedMessage
	(*timestamppb.Timestamp)(nil),          // 16: google.protobuf.Timestamp
}
var file_api_v1_events_transit_proto_depIdxs = []int32{
	15, // 0: transit.events.FeedMessageEvent.feed_message:type_name -> transit_realtime.FeedMessage
	2,  // 1: transit.events.FeedMessageEventCollection.feed_message_events:type_name -> transit.events.FeedMessageEvent
	0,  // 2: transit.events.EventAttributes.stop_status:type_name -> transit.events.StopStatus
	16, // 3: transit.events.EventAttributes.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 4: transit.events.VehiclePositionEvent.attributes:type_name -> transit.events.EventAttributes
	5,  // 5: transit.events.VehiclePositionEventCollection.vehicle_position_events:type_name -> transit.events.VehiclePositionEvent
	4,  // 6: transit.events.StopEvent.attributes:type_name -> transit.events.EventAttributes
	1,  // 7: transit.events.StopEvent.stop_event_type:type_name -> transit.events.StopEvent.EventType
	7,  // 8: transit.events.StopEventCollection.stop_events:type_name -> transit.events.StopEvent
	4,  // 9: transit.events.DwellTimeEvent.attributes:type_name -> transit.events.EventAttributes
	16, // 10: transit.events.DwellTimeEvent.arrival_time:type_name -> google.protobuf.Timestamp
	16, // 11: transit.events.DwellTimeEvent.departure_time:type_name -> google.protobuf.Timestamp
	9,  // 12: transit.events.DwellTimeEventCollection.dwell_time_events:type_name -> transit.events.DwellTimeEvent
	4,  // 13: transit.events.TravelTimeEvent.attributes:type_name -> transit.events.EventAttributes
	16, // 14: transit.events.TravelTimeEvent.start_time:type_name -> google.protobuf.Timestamp
	16, // 15: transit.events.TravelTimeEvent.end_time:type_name -> google.protobuf.Timestamp
	11, // 16: transit.events.TravelTimeEventCollection.travel_time_events:type_name -> transit.events.TravelTimeEvent
	4,  // 17: transit.events.HeadwayTimeEvent.attributes:type_name -> transit.events.EventAttributes
	13, // 18: transit.events.HeadwayTimeEventCollection.headway_time_events:type_name -> transit.events.HeadwayTimeEvent
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_v1_events_transit_proto_init() }
func file_api_v1_events_transit_proto_init() {
	if File_api_v1_events_transit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_events_transit_proto_rawDesc), len(file_api_v1_events_transit_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_events_transit_proto_goTypes,
		DependencyIndexes: file_api_v1_events_transit_proto_depIdxs,
		EnumInfos:         file_api_v1_events_transit_proto_enumTypes,
		MessageInfos:      file_api_v1_events_transit_proto_msgTypes,
	}.Build()
	File_api_v1_events_transit_proto = out.File
	file_api_v1_events_transit_proto_goTypes = nil
	file_api_v1_events_transit_proto_depIdxs = nil
}
